# Server Setting
server:
  servlet:
    encoding:
      charset: utf-8
      force: true
    multipart:
      enabled: true # 파일 업로드 활성화
      max-file-size: 50MB # 단일 파일 최대 크기 설정(1MB)
      max-request-size: 100MB # 전체 요청 최대 크기 설정
  port: 8080

# Logging Setting
logging:
  level:
    root: INFO
    com.tenco: DEBUG


# Spring Setting
spring:
  # Mustache Setting
  mustache:
    servlet:
      expose-session-attributes: false
      expose-request-attributes: false

  # DB Setting
  datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:test
      username: sa
      password:

  # H2 Setting
  h2:
    console:
      enabled: true

  # Initializing DB
  sql:
    init:
      mode: always
      data-locations:
        - classpath:db/data.sql

  # JPA Setting
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

